### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-sibibert#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
7) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу клонування Private GitHub-репозиторіїв. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by msibibert** [comment]
@oleksandrblazhko 

GitHub вирішив перейти на використання персональних токенів доступу (PATs), а не на звичайну аутентифікацію за допомогою імені користувача та пароля для операцій, що стосуються Git, щоб забезпечити більшу безпеку.  
Я бачу ось такі основні причини такого переходу як: 

- підвищення безпеки: Паролі вразливі до різних видів атак, таких як фішинг, відновлення після втрати або розкрадання. PATs можуть бути більш безпечними, оскільки вони не тільки складніші для зламу, але й можуть бути точно обмежені за обсягом прав доступу, які вони надають
- гнучкість доступу: PAT дозволяє визначити точні області доступу, які потрібні для конкретного токена. Наприклад, один токен може мати права лише на читання репозиторіїв, в той час як інший може мати розширені права на зміну репозиторіїв
- легкість управління: Токени легше відкликати та перевіряти, що робить процес управління доступом більш контрольованим і гнучким
- відповідність нормам: Використання PAT допомагає відповідати сучасним стандартам індустрії в області безпеки

**Comment by msibibert-master-cs** [comment]
@oleksandrblazhko 

GitHub вирішив перейти на використання персональних токенів доступу (PATs), а не на звичайну аутентифікацію за допомогою імені користувача та пароля для операцій, що стосуються Git, щоб забезпечити більшу безпеку.

Я бачу ось такі основні причини такого переходу як:

- підвищення безпеки: Паролі вразливі до різних видів атак, таких як фішинг, відновлення після втрати або розкрадання. PATs можуть бути більш безпечними, оскільки вони не тільки складніші для зламу, але й можуть бути точно обмежені за обсягом прав доступу, які вони надають
- гнучкість доступу: PAT дозволяє визначити точні області доступу, які потрібні для конкретного токена. Наприклад, один токен може мати права лише на читання репозиторіїв, в той час як інший може мати розширені права на зміну репозиторіїв
- легкість управління: Токени легше відкликати та перевіряти, що робить процес управління доступом більш контрольованим і гнучким
- відповідність нормам: Використання PAT допомагає відповідати сучасним стандартам індустрії в області безпеки

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
